# Base de données
spring.datasource.url=jdbc:mysql://localhost:3306/dz_cheptel_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# Logs
logging.level.org.hibernate.orm.deprecation=ERROR
logging.level.org.springframework.web=ERROR

# Port
server.port=8080